apiVersion: apps/v1
kind: Deployment
metadata:
    name: tinqin
spec:
    selector:
        matchLabels:
            app: tinqin
    replicas: 2
    template:
        metadata:
            labels:
                app: tinqin
        spec:
            containers:
                - name: tinqin
                  imagePullPolicy: Never
                  image: penyo/devops-u11:$GITHUB_SHA
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: tinqin
spec:
    type: NodePort
    selector:
        app: tinqin
    ports:
        - port: 8080
          targetPort: 8080
