name: Variables
on:  
  push:
    branches:
      - master
jobs:
  deploy:
    name: Test k8s variables
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo code
       uses: actions/checkout@v2
     - name: Try out variables
       run: |
         echo $GITHUB_SHA
         echo $GITHUB_SHA > file.txt
         ls -la
         cat file.txt
         envsubst --help
